export const GET_PRODUCT_REQUEST = `GET_PRODUCT_REQUEST`;
export const GET_PRODUCT_SUCCESS = `GET_PRODUCT_SUCCESS`;
export const GET_PRODUCT_FAILURE = `GET_PRODUCT_FAILURE`;

export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREV_PAGE = "SET_PREV_PAGE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const GET_RANDOM_PRODUCTS = "GET_RANDOM_PRODUCTS";
