export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const INITIATE_SIGNUP = "INITIATE_SIGNUP";
export const INITIATE_LOGIN = "INITIATE_LOGIN";
export const UPDATE_USER_BOOKINGS = "UPDATE_USER_BOOKINGS";
